# myshop-user 公共配置（profile: dev）
spring:
  application:
    name: myshop-user
  rabbitmq:
    host: localhost # 教材示例：192.168.137.20（RabbitMQ 在虚机/Docker 时改对应 IP）
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    bus:
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.150.128:3307/myshop_user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

user:
  instance-tag: 用户微服务-数据源3307

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh

springdoc:
  swagger-ui:
    path: /swagger-ui.html
