# myshop-web（profile: dev）
server:
  port: 9002

spring:
  application:
    name: myshop-web
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    bus:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:7779

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 20

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hystrix.stream,refresh,busrefresh

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.orbitlane.myshopweb
